import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import TopNavbar from "./components/Navbar/TopNavbar";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Blooming Cart | Flower Delivery",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Providers>
          <TopNavbar />
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Toaster position="top-center" reverseOrder={false} />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
